project:
  type: website
  output-dir: docs

website:
  title: "Joan Tan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - blog2.qmd

format:
  html:
    theme: 
      - green_theme.scss
    #css: styles.css
    toc: true

editor: visual

